language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
install:
    - pip install .
script:
    - python setup.py test -q
notifications:
    email: false
virtualenv:
    system_site_packages: true
